import tkinter as tk
import tkinter.messagebox
def clickMe():
    tkinter.messagebox.showinfo(title="Hint", message="測驗結果:0分")
window = tk.Tk()
window.title("iFace v0.2")
window.geometry('1000x1000')
label = tk.Label(window, text="( ͡ °  ͜ʖ﻿  ͡ °)", bg="#15B", fg="#CCF")
label.pack()
label = tk.Label(window, text="智商測驗")
label.pack()
label = tk.Label(window, text="What is your favorite color?")
label.pack()
entry = tk.Entry(window, width = 100)
entry.pack()
label = tk.Label(window, text="What is your favorite food?")
label.pack()
entry = tk.Entry(window, width = 100)
entry.pack()
label = tk.Label(window, text="How many friends do you have?")
label.pack()
entry = tk.Entry(window, width = 100)
entry.pack()
label = tk.Label(window, text="What is your favorite subject?")
label.pack()
entry = tk.Entry(window, width = 100)
entry.pack()
label = tk.Label(window, text="What is your favorite drink?")
label.pack()
entry = tk.Entry(window, width = 100)
entry.pack()
label = tk.Label(window, text="How many IQ are you?")
label.pack()
entry = tk.Entry(window, width = 100)
entry.pack()
label = tk.Label(window, text="Do you like tests?")
label.pack()
button = tk.Button(window, text="Confirm", command=clickMe)
button.pack()
window.mainloop()